version: "3"

networks:
  ingress:
    driver: bridge
  nats:

services:
  nats:
    image: nats:alpine
    restart: always
    command: --jetstream --store_dir /var/lib/nats
    volumes:
      - ${PWD}/.data/nats:/var/lib/nats
    ports:
      - "4222:4222"
    networks:
      - nats
      - ingress

  audit:
    depends_on:
      - nats
    build:
      context: ../
      dockerfile: ./build/package/service.dockerfile
      args:
        SERVICE: audit
        VERSION: ${VERSION:-dev}
    environment:
      BROKER_URI: nats://nats:4222
    networks:
      - nats

  mail:
    depends_on:
      - nats
    build:
      context: ../
      dockerfile: ./build/package/service.dockerfile
      args:
        SERVICE: mail
        VERSION: ${VERSION:-dev}
    environment:
      BROKER_URI: nats://nats:4222
    networks:
      - nats

  gateway-http:
    depends_on:
      - nats
    build:
      context: ../
      dockerfile: ./build/package/service.dockerfile
      args:
        SERVICE: gateway-http
        VERSION: ${VERSION:-dev}
    restart: always
    environment:
      PORT: "8080"
      BROKER_URI: nats://nats:4222
    ports:
      - "80:8080"
    networks:
      - ingress
      - nats
